IMAGE_DIR: "upload/"
DISABLE_SIGN_UP: False

DB_HOST: "localhost"
DB_PORT: "5432"
DB_USER: "postgres"
DB_NAME: "wood"
DB_PASSWD: "mysecretpassword"

EVENT_LOG_FILE: "./wood-event.log"
DB_LOG_FILE: "./wood-db.log"
